import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { X, Copy, Download, Check, ExternalLink, FlaskConical } from "lucide-react";
import { Experiment } from "../mockData";
import { loadMaterials, loadSteps, splitQty } from "../lib/feedbackStore";

// ─── markdown formatter ───────────────────────────────────────────────────────

function formatExperimentMd(exp: Experiment): string {
  // Use scientist-edited data if available, otherwise fall back to plan data
  const steps = loadSteps(exp.id) ?? exp.steps;
  const rawMats = loadMaterials(exp.id);
  const materials = rawMats
    ? rawMats.map((m) => ({
        name: m.name,
        catalog: m.catalog,
        supplier: m.supplier,
        qty: m.qty_unit ? `${m.qty_amount} ${m.qty_unit}` : String(m.qty_amount),
        unit_cost_eur: m.unit_cost_eur,
        total_eur: m.total_eur,
      }))
    : exp.materials.map((m) => {
        const { qty_amount, qty_unit } = splitQty(m.qty);
        return { ...m, total_eur: parseFloat((qty_amount * m.unit_cost_eur).toFixed(2)) };
      });

  const matHeader = "| Reagent | Catalog # | Supplier | Qty | Unit Cost (€) | Subtotal (€) |";
  const matSep    = "|---------|-----------|----------|-----|---------------|--------------|";
  const matRows = materials
    .map((m) => `| ${m.name} | \`${m.catalog}\` | ${m.supplier} | ${m.qty} | ${m.unit_cost_eur} | ${m.total_eur} |`)
    .join("\n");

  return [
    `## ${exp.name}`,
    ``,
    `> **Goal:** ${exp.goal}`,
    `> **Duration:** ${exp.duration}`,
    ``,
    `### Protocol Steps`,
    ``,
    steps.map((s, i) => `${i + 1}. ${s}`).join("\n"),
    ``,
    `### Materials`,
    ``,
    matHeader,
    matSep,
    matRows,
    ``,
    `### Success Criteria`,
    ``,
    exp.success_criteria,
    ``,
    `---`,
    ``,
  ].join("\n");
}

function buildFullDocument(
  hypothesis: string,
  experiments: Experiment[]
): string {
  const header = [
    `# Experiment Plan`,
    ``,
    `**Hypothesis:** ${hypothesis}`,
    ``,
    `Generated by PredictiveBio · ${new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" })}`,
    ``,
    `---`,
    ``,
  ].join("\n");

  return header + experiments.map(formatExperimentMd).join("\n");
}

// ─── component ────────────────────────────────────────────────────────────────

type Props = {
  open: boolean;
  onClose: () => void;
  hypothesis: string;
  experiments: Experiment[];
};

type Tab = "preview" | "api";

export function BenchlingExportModal({ open, onClose, hypothesis, experiments }: Props) {
  const [tab, setTab] = useState<Tab>("preview");
  const [copied, setCopied] = useState(false);

  // Benchling API fields (for future direct-push integration)
  const [apiKey, setApiKey] = useState("");
  const [subdomain, setSubdomain] = useState("");
  const [folderId, setFolderId] = useState("");
  const [apiStatus, setApiStatus] = useState<"idle" | "loading" | "done" | "error">("idle");

  const markdown = buildFullDocument(hypothesis, experiments);

  function copyToClipboard() {
    navigator.clipboard.writeText(markdown).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  function downloadMd() {
    const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "experiment_plan.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  async function pushToBenchling() {
    if (!apiKey || !subdomain || !folderId) return;
    setApiStatus("loading");
    try {
      const res = await fetch("/api/benchling/export", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          benchling_api_key: apiKey,
          subdomain,
          folder_id: folderId,
          hypothesis,
          markdown,
        }),
      });
      if (!res.ok) throw new Error(await res.text());
      setApiStatus("done");
    } catch {
      setApiStatus("error");
    }
  }

  if (!open) return null;

  return (
    <AnimatePresence>
      {open && (
        <>
          {/* Backdrop */}
          <motion.div
            key="backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-40"
            style={{ background: "rgba(0,0,0,0.35)" }}
            onClick={onClose}
          />

          {/* Modal */}
          <motion.div
            key="modal"
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 16 }}
            transition={{ duration: 0.22 }}
            className="fixed inset-x-4 top-[5vh] z-50 mx-auto flex flex-col"
            style={{
              maxWidth: 720,
              maxHeight: "90vh",
              background: "var(--color-card)",
              borderRadius: "var(--radius-card)",
              border: "1px solid var(--color-border)",
              boxShadow: "0 20px 60px rgba(0,0,0,0.18)",
              overflow: "hidden",
            }}
          >
            {/* Header */}
            <div
              className="flex items-center justify-between px-6 py-4 flex-shrink-0"
              style={{ borderBottom: "1px solid var(--color-border)" }}
            >
              <div className="flex items-center gap-2.5">
                <FlaskConical size={18} style={{ color: "var(--color-accent)" }} />
                <span className="font-semibold text-[1rem]" style={{ fontFamily: "var(--font-serif)", color: "var(--color-text)" }}>
                  Export to Benchling
                </span>
              </div>
              <button
                type="button"
                onClick={onClose}
                aria-label="Close"
                className="p-1.5 rounded transition hover:opacity-60"
                style={{ color: "var(--color-text-muted)", background: "none", border: "none" }}
              >
                <X size={18} />
              </button>
            </div>

            {/* Tabs */}
            <div className="flex gap-1 px-6 pt-3 flex-shrink-0" style={{ borderBottom: "1px solid var(--color-border)" }}>
              {(["preview", "api"] as Tab[]).map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setTab(t)}
                  className="px-3 pb-2.5 text-[0.82rem] font-medium transition"
                  style={{
                    background: "none",
                    border: "none",
                    borderBottom: tab === t ? "2px solid var(--color-accent)" : "2px solid transparent",
                    color: tab === t ? "var(--color-text)" : "var(--color-text-muted)",
                    marginBottom: -1,
                  }}
                >
                  {t === "preview" ? "Protocol Preview" : "Direct API Push"}
                </button>
              ))}
            </div>

            {/* Body */}
            <div className="flex-1 overflow-y-auto px-6 py-5">
              {tab === "preview" && (
                <div className="space-y-4">
                  <p className="text-[0.84rem]" style={{ color: "var(--color-text-muted)" }}>
                    The full protocol is formatted as Markdown — paste it directly into a{" "}
                    <a
                      href="https://benchling.com"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="underline"
                      style={{ color: "var(--color-accent-deep)" }}
                    >
                      Benchling
                    </a>{" "}
                    notebook entry, or use the direct push tab once your API key is configured.
                    {loadMaterials(experiments[0]?.id) && (
                      <span style={{ color: "var(--color-accent-deep)" }}> Scientist corrections are included.</span>
                    )}
                  </p>

                  <pre
                    className="text-[0.75rem] leading-relaxed rounded-lg p-4 overflow-x-auto"
                    style={{
                      background: "var(--color-code-bg)",
                      color: "var(--color-code-text)",
                      fontFamily: "var(--font-mono)",
                      whiteSpace: "pre-wrap",
                      wordBreak: "break-word",
                      maxHeight: 360,
                      overflowY: "auto",
                    }}
                  >
                    {markdown}
                  </pre>
                </div>
              )}

              {tab === "api" && (
                <div className="space-y-5">
                  <div
                    className="rounded-lg px-4 py-3 text-[0.82rem] leading-snug"
                    style={{ background: "var(--color-accent-light)", border: "1px solid var(--color-accent)", color: "var(--color-accent-deep)" }}
                  >
                    The backend will call{" "}
                    <code className="text-[0.78rem]" style={{ fontFamily: "var(--font-mono)" }}>
                      POST https://&#123;subdomain&#125;.benchling.com/api/v2/entries
                    </code>{" "}
                    with your credentials and create a notebook entry per experiment. Your key is sent to your own backend only — never stored.
                  </div>

                  <div className="space-y-3">
                    <Field
                      label="Benchling API Key"
                      type="password"
                      placeholder="sk_xxxxxxxxxxxxxxxx"
                      value={apiKey}
                      onChange={setApiKey}
                    />
                    <Field
                      label="Workspace Subdomain"
                      placeholder="your-org  →  your-org.benchling.com"
                      value={subdomain}
                      onChange={setSubdomain}
                    />
                    <Field
                      label="Destination Folder ID"
                      placeholder="lib_xxxxxxxxxxxx"
                      value={folderId}
                      onChange={setFolderId}
                      hint={
                        <a
                          href="https://docs.benchling.com/docs/creating-a-new-notebook-entry-containing-results"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-center gap-1 mt-1 text-[0.75rem] underline"
                          style={{ color: "var(--color-accent-deep)" }}
                        >
                          How to find your folder ID <ExternalLink size={11} />
                        </a>
                      }
                    />
                  </div>

                  {apiStatus === "done" && (
                    <div className="flex items-center gap-2 text-sm" style={{ color: "#2D6A4F" }}>
                      <Check size={14} /> Entries created in Benchling
                    </div>
                  )}
                  {apiStatus === "error" && (
                    <p className="text-sm" style={{ color: "var(--color-coral)" }}>
                      Push failed — check your API key, subdomain, and folder ID.
                    </p>
                  )}
                </div>
              )}
            </div>

            {/* Footer */}
            <div
              className="flex flex-wrap items-center justify-between gap-3 px-6 py-4 flex-shrink-0"
              style={{ borderTop: "1px solid var(--color-border)" }}
            >
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={copyToClipboard}
                  className="inline-flex items-center gap-1.5 px-3 py-2 text-sm font-medium transition hover:opacity-75"
                  style={{
                    background: "transparent",
                    border: "1.5px solid var(--color-border)",
                    borderRadius: 999,
                    color: "var(--color-text)",
                  }}
                >
                  {copied ? <Check size={13} /> : <Copy size={13} />}
                  {copied ? "Copied!" : "Copy Markdown"}
                </button>
                <button
                  type="button"
                  onClick={downloadMd}
                  className="inline-flex items-center gap-1.5 px-3 py-2 text-sm font-medium transition hover:opacity-75"
                  style={{
                    background: "transparent",
                    border: "1.5px solid var(--color-border)",
                    borderRadius: 999,
                    color: "var(--color-text)",
                  }}
                >
                  <Download size={13} />
                  Download .md
                </button>
              </div>

              {tab === "api" && (
                <button
                  type="button"
                  onClick={pushToBenchling}
                  disabled={!apiKey || !subdomain || !folderId || apiStatus === "loading"}
                  className="inline-flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white transition hover:opacity-90 disabled:opacity-40 disabled:cursor-not-allowed"
                  style={{
                    background: "var(--color-accent)",
                    border: "none",
                    borderRadius: 999,
                  }}
                >
                  <FlaskConical size={14} />
                  {apiStatus === "loading" ? "Pushing…" : "Push to Benchling"}
                </button>
              )}
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}

// ─── small helpers ────────────────────────────────────────────────────────────

function Field({
  label, type = "text", placeholder, value, onChange, hint,
}: {
  label: string;
  type?: string;
  placeholder?: string;
  value: string;
  onChange: (v: string) => void;
  hint?: React.ReactNode;
}) {
  return (
    <div>
      <label className="eyebrow mb-1.5 block">{label}</label>
      <input
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full rounded-lg px-3 py-2 text-sm outline-none"
        style={{
          border: "1.5px solid var(--color-border)",
          background: "var(--color-bg)",
          color: "var(--color-text)",
          fontFamily: "var(--font-sans)",
          borderRadius: 8,
        }}
        onFocus={(e) => (e.target.style.borderColor = "var(--color-accent)")}
        onBlur={(e) => (e.target.style.borderColor = "var(--color-border)")}
      />
      {hint}
    </div>
  );
}
